version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FORGE
      VERSION: 1.20.6
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
      SEED: 1691256543523180978
    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt:ro

volumes:
  data:
